#Requires -Version 7.4
<# Tenant-authorized setup for the NEW profile account only. Never lists storage keys or resets populated shares.
   Requires Graph app administration/consent permissions plus ARM role-assignment and VM Run Command permissions. #>
[CmdletBinding()]
param([Parameter(Mandatory)][string]$DeploymentPath,[Parameter(Mandatory)][string]$ReportPath)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Import-Module "$PSScriptRoot/AzureCli.psm1" -Force
$d = Get-Content -LiteralPath $DeploymentPath -Raw | ConvertFrom-Json -AsHashtable
$sub = $d.subscription_id
$account = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('account','show')
if ($account.tenantId -ne $d.tenant_id) { throw 'Wrong tenant for profile setup.' }
if ($d.storage_account -notmatch '^[a-z0-9]{3,24}$') { throw 'Invalid profile storage account.' }
$expected = "[Storage Account] $($d.storage_account).file.core.windows.net"
$apps = @(Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('ad','app','list','--display-name',$expected) | Where-Object { $_['displayName'] -eq $expected })
if ($apps.Count -ne 1) { throw 'Expected exactly one generated Azure Files application. Check Kerberos provisioning/Graph read access and retry.' }
$app = $apps[0]
if (@($app.identifierUris | Where-Object { $_ -eq "api://$($d.tenant_id)/HOST/$($d.storage_account).file.core.windows.net" }).Count -lt 1) {
    throw 'Generated application identifiers do not match this storage account.'
}
# Consent only the documented autogenerated Graph delegated permissions.
$allowed = @('37f7f235-527c-4136-accd-4a02d197296e','14dad69e-099b-42c9-810b-d002981feec1','e1fe6dd8-ba31-4d61-89e7-88639da4683d')
foreach ($resource in $app['requiredResourceAccess']) {
    if ($resource.resourceAppId -ne '00000003-0000-0000-c000-000000000000') { throw 'Unexpected application permission resource; requires tenant review.' }
    foreach ($permission in $resource.resourceAccess) {
        if ($permission.type -ne 'Scope' -or $permission.id -notin $allowed) { throw 'Unexpected application permission; refusing blanket consent.' }
    }
}
$groups = @{}
foreach ($entry in @(@('Finance',$d.finance_group_id),@('Admin',$d.profile_admin_group_id))) {
    $group = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('ad','group','show','--group',$entry[1])
    if (-not $group.securityEnabled) { throw 'Profile groups must be security-enabled.' }
    $sid = if ($group['onPremisesSecurityIdentifier']) { $group['onPremisesSecurityIdentifier'] } else { $group['securityIdentifier'] }
    if (-not $sid) { throw 'Graph did not return a supported group SID. Do not derive or invent one.' }
    $groups[$entry[0]]=$sid
}
$uris = @($app.identifierUris)
foreach ($uri in @($app.identifierUris)) {
    if ($uri.EndsWith("$($d.storage_account).file.core.windows.net",[StringComparison]::OrdinalIgnoreCase)) {
        $uris += $uri.Replace("$($d.storage_account).file.core.windows.net","$($d.storage_account).privatelink.file.core.windows.net")
    }
}
$body = @{identifierUris=@($uris | Select-Object -Unique); tags=@(@($app['tags'])+'kdc_enable_cloud_group_sids' | Where-Object { $_ } | Select-Object -Unique)}
$payload = Join-Path ([IO.Path]::GetTempPath()) ("sportfive-graph-$([guid]::NewGuid()).json")
$guestFile = Join-Path ([IO.Path]::GetTempPath()) ("sportfive-acl-$([guid]::NewGuid()).ps1")
$roleId = $null
try {
    [IO.File]::WriteAllText($payload,($body | ConvertTo-Json -Depth 8))
    $null = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('rest','--method','patch','--url',"https://graph.microsoft.com/v1.0/applications/$($app.id)",'--body',"@$payload")
    $null = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('ad','app','permission','admin-consent','--id',$app.appId)
    $vm = @($d.hosts.Values | Sort-Object name)[0]
    $instance = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('vm','get-instance-view','--ids',$vm.id)
    if (@($instance.instanceView.statuses | Where-Object { $_.code -eq 'PowerState/running' }).Count -ne 1) {
        $null = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('vm','start','--ids',$vm.id)
    }
    $details = Invoke-AvdArm -SubscriptionId $sub -Path "$($vm.id)?api-version=2024-07-01"
    $principal = $details['identity']['principalId']
    if (-not $principal) { throw 'Session host has no managed identity.' }
    # Temporary privilege confined to this profile share, always revoked in finally.
    $name = [guid]::NewGuid().ToString()
    $role = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('role','assignment','create','--name',$name,
        '--assignee-object-id',$principal,'--assignee-principal-type','ServicePrincipal','--role','Storage File Data Privileged Contributor','--scope',$d.profile_share_id)
    $roleId=$role.id
    if ($role.name -ne $name) { throw 'Unexpected role assignment response; inspect before proceeding.' }
    $config = @{Account=$d.storage_account;Share='profiles';FinanceSid=$groups.Finance;AdminSid=$groups.Admin} | ConvertTo-Json -Compress
    $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($config))
    $source = Get-Content "$PSScriptRoot/../hosts/Initialize-ProfileRoot.ps1" -Raw
    $script = "& {`n$source`n} -ConfigurationJson ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('$encoded')))"
    [IO.File]::WriteAllText($guestFile,$script)
    $result = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('vm','run-command','invoke','--ids',$vm.id,'--command-id','RunPowerShellScript','--scripts',"@$guestFile")
    $messages = @($result.value | ForEach-Object { $_.message }) -join "`n"
    $jsonLine = @($messages -split "`n" | Where-Object { $_.Trim().StartsWith('{') } | Select-Object -Last 1)
    if ($jsonLine.Count -ne 1) { throw 'Profile ACL initialization returned no structured success evidence.' }
    $acl = $jsonLine[0] | ConvertFrom-Json -AsHashtable
    if ($acl['schemaVersion'] -ne '1.0' -or $acl['passed'] -ne $true) { throw 'Profile ACL initialization failed.' }
    $report = @{schemaVersion='1.0';completedUtc=[datetimeoffset]::UtcNow.ToString('o');storageApplicationId=$app.appId;acl=$acl;
        conditionalAccessValidated=$false;userSignInValidated=$false}
    [IO.File]::WriteAllText($ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($ReportPath),($report | ConvertTo-Json -Depth 12))
    Write-Host 'Storage application consent/private-link/group claims and root ACL setup completed. Tenant CA/SSO and real sign-in still require acceptance.'
} finally {
    if ($roleId) { $null = Invoke-AvdAzureCli -SubscriptionId $sub -Arguments @('role','assignment','delete','--ids',$roleId) }
    foreach ($file in @($payload,$guestFile)) { if (Test-Path -LiteralPath $file) { Remove-Item -LiteralPath $file } }
}
